Controllers/bookController.cs
using bookecommercewebsite.Models;
using Dapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace bookecommercewebsite.Controllers
{
    public class bookController : Controller
    {

        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly bookecommerceContext adb;

        public bookController(IWebHostEnvironment hostEnvironment)
        {

            webHostEnvironment = hostEnvironment;

        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("role") == "admin")
            {
                IDbConnection connection = new SqlConnection(Dapper.Connection);
                connection.Open();
                var data = connection.Query<Book>("select book.bookid, book.bookname, book.bookauthor, book.bookprice, book.bookimage, bookcat.bookcatname from book inner join bookcat on book.bookcatid = bookcat.bookcatid");
                return View(data);
            }
            else
            {
                return RedirectToAction(controllerName: "Login", actionName: "Index");
            }

        }
        //
        // GET: Customer/Create
        public ActionResult Create()
        {
            if (HttpContext.Session.GetString("role") == "admin")
            {
                var book = new Bookcat();
                IDbConnection connection = new SqlConnection(Dapper.Connection);
                var bookdata = connection.Query<Bookcat>("select * from bookcat").ToList();
                ViewBag.TotalSubs = new SelectList(bookdata, "Bookcatid", "Bookcatname");
                return View();
            }
            else
            {
                return RedirectToAction(controllerName: "Login", actionName: "Index");
            }
        }

        // POST: Customer/Create
        [HttpPost]
        public async Task<IActionResult> Create(Book book, IFormFile ifile)
        {

            if (HttpContext.Session.GetString("role") == "admin")
            {

                try
                {


                    using (IDbConnection db = new SqlConnection(Dapper.Connection))
                    {
                        string imgext = Path.GetExtension(ifile.FileName);
                        if (imgext == ".jpg" || imgext == ".gif" || imgext == ".PNG")
                        {
                            var saveimg = Path.Combine(webHostEnvironment.WebRootPath, ("Images"), ifile.FileName);
                            var stream = new FileStream(saveimg, FileMode.Create);
                            await ifile.CopyToAsync(stream);

                            book.Bookimage = ifile.FileName;



                            var bookdata = db.Query<Bookcat>("select * from bookcat").ToList();
                            ViewBag.TotalSubs = new SelectList(bookdata, "Bookcatid", "Bookcatname");
                            db.Open();
                            string sqlQuery = "Insert Into book ( Bookname, Bookauthor, Bookprice, Bookimage, Bookcatid) Values( @Bookname, @Bookauthor, @Bookprice, @Bookimage, @Bookcatid)";

                            var rowsAffected = db.Execute(sqlQuery, new { Bookname = book.Bookname, Bookauthor = book.Bookauthor, Bookprice = book.Bookprice, Bookimage = book.Bookimage, Bookcatid = book.Bookcatid });
                        }
                    }

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return View();
                }
            }
            else
            {
                return RedirectToAction(controllerName: "Login", actionName: "Index");
            }
        }


        public ActionResult Edit(int id)
        {
            if (HttpContext.Session.GetString("role") == "admin")
            {
                Book book = new Book();
                using (IDbConnection db = new SqlConnection(Dapper.Connection))
                {
                    var bookdata = db.Query<Bookcat>("select * from bookcat").ToList();
                    ViewBag.TotalSubs = new SelectList(bookdata, "Bookcatid", "Bookcatname");
                    book = db.Query<Book>("select book.bookid, book.bookname, book.bookauthor, book.bookprice, book.bookimage, bookcat.bookcatname from book inner join bookcat on book.bookcatid = bookcat.bookcatid WHERE Bookid =" + id, new { id }).SingleOrDefault();//only takes single value or default value
                }
                return View(book);
            }
            else
            {
                return RedirectToAction(controllerName: "Login", actionName: "Index");
            }
        }

        // POST: Customer/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Book books, IFormFile ifile)
        {
            if (HttpContext.Session.GetString("role") == "admin")
            {



                string imgext = Path.GetExtension(ifile.FileName);
                if (imgext == ".jpg" || imgext == ".gif" || imgext == ".PNG")
                {
                    var a = DateTime.Now.Ticks + ifile.FileName;
                    var saveimg = Path.Combine(webHostEnvironment.WebRootPath, ("Images"), a);
                    var stream = new FileStream(saveimg, FileMode.Create);
                    await ifile.CopyToAsync(stream);

                    books.Bookimage = a;
                    using (IDbConnection db = new SqlConnection(Dapper.Connection))
                    {
                        var bookdata = db.Query<Bookcat>("select * from bookcat").ToList();
                        ViewBag.TotalSubs = new SelectList(bookdata, "Bookcatid", "Bookcatname");
                    }

                    string sqlQuery = "UPDATE book set bookname=@bookname, bookauthor=@bookauthor, bookprice=@bookprice, bookimage=@bookimage, bookcatid=@bookcatid WHERE bookid=@bookid";

                    DynamicParameters parameters = new DynamicParameters();
                    parameters.Add("@bookname", books.Bookname);
                    parameters.Add("@bookauthor", books.Bookauthor);
                    parameters.Add("@bookprice", books.Bookprice);
                    parameters.Add("@bookimage", books.Bookimage);
                    parameters.Add("@bookcatid", books.Bookcatid);
                    parameters.Add("@bookid", id);

                    var data = Class1.RunQuery<Book>(sqlQuery, parameters);
                    
                }

            }
            else
            {
                return RedirectToAction(controllerName: "Login", actionName: "Index");
            }
            return RedirectToAction("Index");
        }
    
        public ActionResult Details(int id)
        {
            if (HttpContext.Session.GetString("role") == "admin")
            {
                Book book = new Book();
                using (IDbConnection db = new SqlConnection(Dapper.Connection))
                {

                    book = db.Query<Book>("select book.bookid, book.bookname, book.bookauthor, book.bookprice, book.bookimage, bookcat.bookcatname from book inner join bookcat on book.bookcatid = bookcat.bookcatid WHERE Bookid =" + id, new { id }).SingleOrDefault();//only takes single value or default value
                }
                return View(book);
            }
            else
            {
                return RedirectToAction(controllerName: "Login", actionName: "Index");
            }
        }

        // POST: 
        [HttpPost]
        public ActionResult Details(int id, Book book)
        {
            if (HttpContext.Session.GetString("role") == "admin")
            {
                try
                {
                    using (IDbConnection db = new SqlConnection(Dapper.Connection))
                    {
                        string sqlQuery = "Select book from Bookname='" + book.Bookname +
                             "',Bookauthor='" + book.Bookauthor +
                             "',Bookprice='" + book.Bookprice +
                             "',Bookimage='" + book.Bookprice +
                              "',Bookcatname='" + book.Bookcatname +
                             "' WHERE Bookid=" + id;

                        int rowsAffected = db.Execute(sqlQuery);
                    }

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return View();
                }
            }
            else
            {
                return RedirectToAction(controllerName: "Login", actionName: "Index");
            }
        }
        public ActionResult Delete(int id)
        {
            if (HttpContext.Session.GetString("role") == "admin")
            {
                Book book = new Book();
                using (IDbConnection db = new SqlConnection(Dapper.Connection))
                {
                    var bookdata = db.Query<Bookcat>("select * from bookcat").ToList();
                    ViewBag.TotalSubs = new SelectList(bookdata, "Bookcatid", "Bookcatname");
                    book = db.Query<Book>("select book.bookid, book.bookname, book.bookauthor, book.bookprice, bookcat.bookcatname from book inner join bookcat on book.bookcatid = bookcat.bookcatid WHERE Bookid =" + id, new { id }).SingleOrDefault();
                }
                return View(book);
            }
            else
            {
                return RedirectToAction(controllerName: "Login", actionName: "Index");
            }
        }

        // POST: Customer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Bookcat bookcat)
        {
            if (HttpContext.Session.GetString("role") == "admin")
            {

Controllers/contactController.cs
using bookecommercewebsite.Models;
using Dapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace bookecommercewebsite.Controllers
{
    public class contactController : Controller
    {
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("role") == "admin")
            {
                IDbConnection connection = new SqlConnection(Dapper.Connection);
                connection.Open();
                var data = connection.Query<Contact>("select contact.contactid, contact.contactname, contact.contactemail, contact.contactsubject, contact.contactnotes from contact");
                return View(data);
            }
            else
            {
                return RedirectToAction(controllerName: "Login", actionName: "Index");
            }
        }


        public ActionResult Create()
        {
            
                return View();
           
        }

        // POST: Customer/Create
        [HttpPost]
        public ActionResult Create(Contact contact)
        {
          
                try
                {
                    using (IDbConnection db = new SqlConnection(Dapper.Connection))
                    {
                        db.Open();
                        string sqlQuery = "Insert Into contact ( contactname, contactemail, contactsubject, contactnotes ) Values(  @contactname, @contactemail, @contactsubject, @contactnotes)";

                        var rowsAffected = db.Execute(sqlQuery, new { contactname = contact.Contactname, contactemail = contact.Contactemail, contactsubject = contact.Contactsubject, contactnotes = contact.Contactnotes });
                    }

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return View();
                }
            
        }


        public ActionResult Delete(int id)
        {
            if (HttpContext.Session.GetString("role") == "admin")
            {
                Contact contact = new Contact();
                using (IDbConnection db = new SqlConnection(Dapper.Connection))
                {
                    contact = db.Query<Contact>("Select * From contact WHERE contactid =" + id, new { id }).SingleOrDefault();
                }
                return View(contact);
            }
            else
            {
                return RedirectToAction(controllerName: "Login", actionName: "Index");
            }
        }

        // POST: Customer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Contact contact)
        {
            if (HttpContext.Session.GetString("role") == "admin")
            {
                try
                {
                    using (IDbConnection db = new SqlConnection(Dapper.Connection))
                    {
                        string sqlQuery = "Delete From contact WHERE contactid = " + id;

                        int rowsAffected = db.Execute(sqlQuery);
                    }

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return View();
                }
            }
            else
            {
                return RedirectToAction(controllerName: "Login", actionName: "Index");
            }
        }


    }
}

Controllers/orderController.cs
using bookecommercewebsite.Models;
using Dapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace bookecommercewebsite.Controllers
{
    public class orderController : Controller
    {
        public IActionResult Index()
        {
            int Status = 1;
            IDbConnection connection = new SqlConnection(Dapper.Connection);
            connection.Open();

            //var data = connection.Query<Cart>("select cart.userid, cart.bookid, book.bookname, book.bookauthor, book.bookprice, book.bookimage from cart join book on cart.bookid = book.bookid where status = "+ Status);
            var data = connection.Query<Order>("select [order].orderid, [order].userid, [order].bookid, book.bookname, [order].quantity, [order].status, [order].fullname, [order].email, [order].phonenumber, book.bookauthor, book.bookprice, book.bookimage from [order] join book on [order].bookid = book.bookid where status =" + Status);
            return View(data);

        }


        // GET: Order/Edit
        public ActionResult Edit(int id)
        {
            User user = new User();
            string sql = "select fullname, email, phonenumber from [order] where userid=@userid";
            DynamicParameters parameters = new DynamicParameters();
            parameters.Add("@userid", HttpContext.Session.GetString("userid"));


            var data = Class1.RunQuery<Order>(sql, parameters).FirstOrDefault();
            return View(data);
        }


        [HttpPost]
        public ActionResult Edit(int id, Order order)
        {


            string sqlQuery = "UPDATE [order] set fullname=@fullname, email=@email, phonenumber=@phonenumber WHERE userid=@userid";

            DynamicParameters parameters = new DynamicParameters();
            parameters.Add("@fullname", order.Fullname);
            parameters.Add("@email", order.Email);
            parameters.Add("@phonenumber", order.Phonenumber);
         
            parameters.Add("@userid", HttpContext.Session.GetString("userid"));

            var data = Class1.RunQuery<Order>(sqlQuery, parameters);


            return RedirectToAction(controllerName: "cart", actionName: "Index");

        }


        public ActionResult Delete(int id)
        {
            if (HttpContext.Session.GetString("role") == "admin")
            {
                Order order = new Order();
                using (IDbConnection db = new SqlConnection(Dapper.Connection))
                {
                   
                    order = db.Query<Order>("select [order].orderid, [order].userid, [order].bookid, book.bookname, [order].quantity, [order].status, [order].fullname, [order].email, [order].phonenumber, book.bookauthor, book.bookprice, book.bookimage from[order] join book on[order].bookid = book.bookid where orderid = " + id, new { id }).SingleOrDefault();
                }
                return View(order);
            }
            else
            {
                return RedirectToAction(controllerName: "Login", actionName: "Index");
            }
        }

        // POST: Customer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Order bookcat)
        {
            if (HttpContext.Session.GetString("role") == "admin")
            {
               
                    using (IDbConnection db = new SqlConnection(Dapper.Connection))
                    {
                      
                        string sqlQuery = "Delete From [order] WHERE orderid = " + id;

                        int rowsAffected = db.Execute(sqlQuery);
                    }

                    return RedirectToAction("Index");
             
            }
            else
            {
                return RedirectToAction(controllerName: "Login", actionName: "Index");
            }
        }


    }
}

Views/Users/Details.cshtml
@model bookecommercewebsite.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bookname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bookname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bookauthor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bookauthor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bookprice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bookprice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bookcatid)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bookcatid)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bookcatname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bookcatname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bookimage)
        </dt>
        <dd class="col-sm-10">
            <img src="~/images/@Html.DisplayFor(model => model.Bookimage)" height="200" width="180" />
        </dd>
    </dl>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.Bookid">Edit</a> |*@
    <a asp-action="addtocart" asp-route-id="@Model.Bookid">Add to Cart</a>
  <br/>
    <a asp-action="Index">Back to List</a>
</div>

Views/Users/Index.cshtml
@using Microsoft.AspNetCore.Http;




@if (@Context.Session.GetString("role") == "customer")
{
    <!-- Main -->
    <div id="main">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="images/slider-image-1-1920x700.jpg" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="images/slider-image-2-1920x700.jpg" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="images/slider-image-3-1920x700.jpg" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <br>
        <br>

        <div class="inner">
            <!-- About Us -->
            <header id="inner">
                <h1>Find your new book!</h1>

            </header>

            <br>


            <h2 class="h2">Featured Products</h2>

            <!-- Products -->
            @model IEnumerable<bookecommercewebsite.Models.Book>

            @{
                ViewData["Title"] = "Index";
            }



            @*<p>
                    <a asp-action="Create">Create New</a>
                </p>*@
            <div class="row">
                @foreach (var book in Model)
                {
                    <div class="col-4">
                        <div class="card mb-4">
                            <div class="card-header">

                                <img src="~/images/@book.Bookimage" alt="Card Image" height="200" width="120" class="card-img-top" />
                                <label style="font-size:23px;color: steelblue"><b>Name:&nbsp;</b>@book.Bookname</label>
                                <p><b>Author:&nbsp;</b>@book.Bookauthor</p>
                                <p><b>Price:&nbsp;</b>@book.Bookprice</p>
                                <p><b>Category:&nbsp;</b>@book.Bookcatname</p>

                                <a asp-action="Details" asp-route-id="@book.Bookid">Details</a>

                            </div>
                        </div>
                    </div>
                }
            </div>








            <br>







        </div>
    </div>

    <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <section>
                <a asp-controller="contact" asp-action="Create">Contact Us</a>

            </section>


            <ul class="copyright">
                <li>Copyright © 2020 Company Name </li>
                <li>Template by: <a href="https://www.phpjabbers.com/">PHPJabbers.com</a></li>
            </ul>
        </div>
    </footer>
}
else if (@Context.Session.GetString("role") == "admin")
{

    <div class="container">
        <ul class="">

            <li>
                <a class="" asp-controller="bookcat" asp-action="Index">

                    <span class="">Add Book Category</span>
                </a>
            </li>


            <li>
                <a class="" asp-controller="book" asp-action="Index">

                    <span class="">Add Book</span>
                </a>

            </li>

            <li>
                <a class="" asp-controller="order" asp-action="Index">

                    <span class="">View Order</span>
                </a>

            </li>
            <li>
                <a class="" asp-controller="contact" asp-action="Index">

                    <span class="">View Feedback</span>
                </a>

            </li>



        </ul>
    </div>
}
else
{
    <div id="main">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="images/slider-image-1-1920x700.jpg" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="images/slider-image-2-1920x700.jpg" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="images/slider-image-3-1920x700.jpg" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <br>
        <br>

        <div class="inner">
            <!-- About Us -->
            <header id="inner">
                <h1>Find your new book!</h1>

            </header>

            <br>

            <h2 class="h2">Featured Products</h2>

            <!-- Products -->


            @{
                ViewData["Title"] = "Index";
            }



            @*<p>
                    <a asp-action="Create">Create New</a>
                </p>*@
            <div class="row">
                @foreach (var book in Model)
                {
                    <div class="col-4">
                        <div class="card mb-4">
                            <div class="card-header">

                                <img src="~/images/@book.Bookimage" alt="Card Image" height="200" width="120" class="card-img-top" />
                                <label style="font-size:23px;color: steelblue"><b>Name:&nbsp;</b>@book.Bookname</label>
                                <p><b>Author:&nbsp;</b>@book.Bookauthor</p>
                                <p><b>Price:&nbsp;</b>@book.Bookprice</p>
                                <p><b>Category:&nbsp;</b>@book.Bookcatname</p>

                                <a asp-action="Details" asp-route-id="@book.Bookid">Details</a>

                            </div>
                        </div>
                    </div>
                }
            </div>








            <br>







        </div>
    </div>

    <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <section>
                <a asp-controller="contact" asp-action="Create">Contact Us</a>

            </section>


            <ul class="copyright">
                <li>Copyright © 2020 Company Name </li>
                <li>Template by: <a href="https://www.phpjabbers.com/">PHPJabbers.com</a></li>
            </ul>
        </div>
    </footer>
}
        </div>








<br>







                </div>
            </div>
        }
    </div>

<!-- Scripts -->
<script src="assets/js/jquery.min.js"></script>
<script src="assets/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="assets/js/jquery.scrolly.min.js"></script>
<script src="assets/js/jquery.scrollex.min.js"></script>
<script src="assets/js/main.js"></script>


</html>